config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :articles
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])
  end

  def create
    @article = Article.create(article_params)
    redirect_to articles_path
  end

  def new
     @article = Article.new
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])
    @article.update(article_params)
    redirect_to articles_path
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy
    redirect_to articles_path
  end

  private

  def article_params
    params.require(:article).permit(:title, :content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/edit.html.erb
<div class="container">
  <div class="row">
    <div class="formulaire">

      <%= form_for(@article) do |f| %>
    <%= f.label :title %>
    <%= f.text_field :title %>

    <%= f.label :content %>
    <%= f.text_field :content %>

    <%= f.submit %>
  <% end %>

    </div>
  </div>
</div>

app/views/articles/index.html.erb
<div class="container">
  <div class="row">
    <h1>Wikinimous</h1>
    <% @articles.each do |article| %>
      <div class="articles">
        <p><%= link_to article.title, article_path(article) %></p>
      </div>
    <% end %>
    <div class="btn btn-warning">
    <p><%= link_to "Add a new article", new_article_path %></p>
    </div>
  </div>
</div>

app/views/articles/new.html.erb
<div class="container">
  <div class="row">
    <div class="formulaire">

      <%= form_for(@article) do |f| %>
    <%= f.label :title %>
    <%= f.text_field :title %>

    <%= f.label :content %>
    <%= f.text_field :content %>

    <%= f.submit %>
  <% end %>
    </div>
  </div>
</div>

app/views/articles/show.html.erb
<div class="container">
  <div class="row">
    <h2><%= @article.title %></h2>
    <div class="details">
      <p><%= @article.content %></p>
    </div>

    <%= link_to "Back to list", articles_path %>
<br />
    <%= link_to "Edit", edit_article_path %>
    <%= link_to '<i class="fa fa-trash" aria-hidden="true"></i>'.html_safe, article_path,
              method: :delete,
              data: { confirm: "Are you sure?" } %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWikinimous</title>
    <%= csrf_meta_tags %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>